parameters:
#    d2_nit_blog.example.class: D2Nit\BlogBundle\Example

services:
#    d2_nit_blog.example:
#        class: %d2_nit_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
